services:
  mongodb:
    image: mongo:7.0
    container_name: pollix-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pollix_db
    
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: pollix-mongodb-data
